apiVersion: v1
kind: Service
metadata:
  name: client-service-green
  namespace: prod
spec:
  selector:
    app: client
    color: green
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
