apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment-green
  namespace: prod
  labels:
    app: comments
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
      color: green
  template:
    metadata:
      labels:
        app: comments
        color: green
    spec:
      containers:
        - name: comments
          image: 293337163121.dkr.ecr.us-east-1.amazonaws.com/comments:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          env:
            - name: EVENT_BUS_URL
              value: "http://event-bus-svc-green.prod.svc.cluster.local:4005"
