apiVersion: v1
kind: Service
metadata:
  name: event-bus-svc
  namespace: prod-green
spec:
  selector:
    app: event-bus
    color: green
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
  type: ClusterIP
