apiVersion: v1
kind: Service
metadata:
  name: comments-svc
  namespace: qa
spec:
  selector:
    app: comments

  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
