apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: ${{ secrets.ECR_EVENTBUS_URI }}:latest
          ports:
            - containerPort: 4005
          env:
            - name: POSTS_URL
              value: "http://posts-service:4000"
            - name: COMMENTS_URL
              value: "http://comments-service:4001"
            - name: QUERY_URL
              value: "http://query-service:4002"
