apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  namespace: qa
  labels:
    app: event-bus
    color: green
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
      color: green
  template:
    metadata:
      labels:
        app: event-bus
        color: green
    spec:
      containers:
        - name: event-bus
          image: 293337163121.dkr.ecr.us-east-1.amazonaws.com/event-bus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
          env:
            - name: POSTS_URL
              value: "http://posts-svc.qa.svc.cluster.local:4000"
            - name: COMMENTS_URL
              value: "http://comments-svc.qa.svc.cluster.local:4001"
            - name: QUERY_URL
              value: "http://query-svc.qa.svc.cluster.local:4002"
