apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: qa
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: posts-svc
                port:
                  number: 4000
          - path: /comments
            pathType: Prefix
            backend:
              service:
                name: comments-svc
                port:
                  number: 4001
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: query-svc
                port:
                  number: 4002
          - path: /event-bus
            pathType: Prefix
            backend:
              service:
                name: event-bus-svc
                port:
                  number: 4005
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80
