apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: qa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: ^/posts(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: posts-svc
                port:
                  number: 4000
          
          - path: ^/comments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments-svc
                port:
                  number: 4001
          
          - path: ^/query(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: query-svc
                port:
                  number: 4002
