apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: ${{ secrets.ECR_POSTS_URI }}:latest
          ports:
            - containerPort: 4000
