apiVersion: v1
kind: Service
metadata:
  name: event-bus-svc
  namespace: uat
spec:
  selector:
    app: event-bus

  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
  type: ClusterIP
