#!/bin/sh
cat <<EOF > /usr/share/nginx/html/env-config.js
window.REACT_APP_COMMENTS_SERVICE_URL="$REACT_APP_COMMENTS_SERVICE_URL";
window.REACT_APP_POSTS_SERVICE_URL="$REACT_APP_POSTS_SERVICE_URL";
window.REACT_APP_QUERY_SERVICE_URL="$REACT_APP_QUERY_SERVICE_URL";
window.REACT_APP_EVENTBUS_SERVICE_URL="$REACT_APP_EVENTBUS_SERVICE_URL";
EOF

exec nginx -g "daemon off;"
