apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: ${{ secrets.ECR_COMMENTS_URI }}:latest
          ports:
            - containerPort: 4001
