apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
  namespace: qa
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
  type: ClusterIP
