version: "3.8"

services:
  posts:
    build: ./posts
    ports:
      - "4000:4000"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
    restart: always

  comments:
    build: ./comments
    ports:
      - "4001:4001"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
    restart: always

  query:
    build: ./query
    ports:
      - "4002:4002"
    restart: always

  event-bus:
    build: ./event-bus
    ports:
      - "4005:4005"
    environment:
      - POSTS_URL=http://posts:4000
      - COMMENTS_URL=http://comments:4001
      - QUERY_URL=http://query:4002
    restart: always

  client:
    build: ./client
    ports:
      - "3000:80" # React app served by nginx inside container
    restart: always
