apiVersion: v1
kind: Service
metadata:
  name: posts-svc
  namespace: prod
spec:
  selector:
    app: posts
    color: blue
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
