name: Build Client for QA

on:
  workflow_dispatch: {}

jobs:
  build-client:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "tag=qa-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Client Image
        working-directory: blog/client
        run: |
          export $(cat .env.qa | xargs)
          docker build \
            --build-arg REACT_APP_COMMENTS_SERVICE_URL=$REACT_APP_COMMENTS_SERVICE_URL \
            --build-arg REACT_APP_QUERY_SERVICE_URL=$REACT_APP_QUERY_SERVICE_URL \
            --build-arg REACT_APP_POSTS_SERVICE_URL=$REACT_APP_POSTS_SERVICE_URL \
            --build-arg REACT_APP_EVENTBUS_SERVICE_URL=$REACT_APP_EVENTBUS_SERVICE_URL \
            -t ${{ secrets.ECR_CLIENT_URI }}:${{ env.tag }} .
          docker push ${{ secrets.ECR_CLIENT_URI }}:${{ env.tag }}

      - name: Save Tag as Artifact
        run: echo "${{ env.tag }}" > client-qa.tag

      - name: Upload Tag Artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-qa-tag
          path: client-qa.tag


