name: Build and Push Event-Bus Service

on:
  pull_request:
    paths:
      - 'blog/event-bus/**'
  workflow_dispatch: {}

jobs:
  build-push-eventbus:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Timestamp
        id: vars
        run: echo "timestamp=$(date -u +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_EVENTBUS_URI }} ./blog/event-bus
          docker tag ${{ secrets.ECR_EVENTBUS_URI }}:latest ${{ secrets.ECR_EVENTBUS_URI }}:${{ env.timestamp }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ECR_EVENTBUS_URI }}:${{ env.timestamp }}
          docker push ${{ secrets.ECR_EVENTBUS_URI }}:latest
