name: Build and Push Client Service (QA)

on:
  pull_request:
    paths:
      - 'blog/client/**'
  workflow_dispatch: {}

jobs:
  build-push-client:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        id: vars
        run: echo "tag=qa-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Load .env.qa and Build Image
        working-directory: blog/client
        run: |
          export $(cat .env.qa | xargs)
          docker build \
            --build-arg REACT_APP_COMMENTS_SERVICE_URL=$REACT_APP_COMMENTS_SERVICE_URL \
            --build-arg REACT_APP_QUERY_SERVICE_URL=$REACT_APP_QUERY_SERVICE_URL \
            --build-arg REACT_APP_POSTS_SERVICE_URL=$REACT_APP_POSTS_SERVICE_URL \
            --build-arg REACT_APP_EVENTBUS_SERVICE_URL=$REACT_APP_EVENTBUS_SERVICE_URL \
            -t ${{ secrets.ECR_CLIENT_URI }}:${{ env.tag }} .

      - name: Push QA Image to ECR
        run: |
          docker push ${{ secrets.ECR_CLIENT_URI }}:${{ env.tag }}

