name: Build and Push Query Service

on:
  pull_request:
    paths:
      - "blog/query/**"
  workflow_dispatch: {}

jobs:
  build-push-query:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Timestamp
        id: vars
        run: echo "timestamp=$(date -u +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_QUERY_URI }} ./blog/query
          docker tag ${{ secrets.ECR_QUERY_URI }}:latest ${{ secrets.ECR_QUERY_URI }}:${{ env.timestamp }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ECR_QUERY_URI }}:${{ env.timestamp }}
          docker push ${{ secrets.ECR_QUERY_URI }}:latest

      - name: Trigger QA Deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy All Services to QA
          token: ${{ secrets.GITHUB_TOKEN }}
