name: Build and Push Comments Service

on:
  pull_request:
    paths:
      - 'blog/comments/**'
  workflow_dispatch: {}

jobs:
  build-push-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Timestamp
        id: vars
        run: echo "timestamp=$(date -u +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_COMMENTS_URI }} ./comments
          docker tag ${{ secrets.ECR_COMMENTS_URI }}:latest ${{ secrets.ECR_COMMENTS_URI }}:${{ env.timestamp }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ECR_COMMENTS_URI }}:${{ env.timestamp }}
