name: Deploy Client to QA

on:
  workflow_dispatch: {}

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Image Tag
        uses: actions/download-artifact@v4
        with:
          name: client-qa-tag

      - name: Read Tag
        id: tag
        run: |
          TAG=$(cat client-qa.tag)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "Using client image: $TAG"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy client with image ${{ env.IMAGE_TAG }}
        run: |
          kubectl set image deployment/client-deployment \
            client=${{ secrets.ECR_CLIENT_URI }}:${{ env.IMAGE_TAG }} \
            -n qa

      - name: Verify Deployment + Test Ingress
        run: |
          kubectl rollout status deployment/client-deployment -n qa
          INGRESS=$(kubectl get ingress app-ingress -n qa -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          echo "Testing: http://$INGRESS"
          curl -I --retry 10 --retry-delay 5 http://$INGRESS
